#
# (c) Copyright 2015-2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
- include: keystone-status.yml

- hosts: KEY-API
  roles:
    - role: KEY-API
  tasks:
    - include: roles/KEY-API/tasks/install.yml


- hosts: KEY-API
  roles:
    - role: KEY-API
  tasks:
    - include: roles/KEY-API/tasks/db_configure.yml

- hosts: KEY-API
  roles:
    - KEY-API
  tasks:
    - include: roles/KEY-API/tasks/configure.yml
      ansible_python_interpreter: "{{
        KEY_CLI.vars.keystone_client_python_interpreter }}"

- hosts: KEY-API
  serial: 1
  roles:
    - role: KEY-API
  tasks:
    - include: roles/KEY-API/tasks/start.yml

# provision any new users, services, endpoints, etc.
# NOTE: all operations should be idempotent
- hosts: KEY-API
  roles:
    - role: keystone-post-configure
  tasks:
    - include: roles/keystone-post-configure/tasks/keystone_provision_accts.yml
      ansible_python_interpreter: "{{
        KEY_CLI.vars.keystone_client_python_interpreter }}"

- include: keystone-status.yml
