#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: keystone-monitor | monitor_fernet_master_node |
        Check Fernet token configuration prereq
  debug:
    msg: >-
      WARNING: Then number of play hosts does not match the number of Keystone
      API hosts. It is possible that the --limit option was used in the play.
      The use of --limit option is not supported when configuring the
      Fernet token feature. Fernet token configuration will be skipped.
  when: vars['play_hosts'] | length != keystone_hosts | length

- name: keystone-monitor | monitor_fernet_master_node | Monitor Fernet Master
  include: _monitor_fernet_master_node.yml
  when: vars['play_hosts'] | length == keystone_hosts | length
