#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
# see if fernet master node alread exist
- include: _find_fernet_master_node.yml

# If the master node exist, fernet_master_node should be defined. Otherwise,
# we'll designate the first node as the master node.
- name: KEY-API | _set_fernet_master_node | Set Fernet master node
  set_fact:
    fernet_master_node: "{{ keystone_hosts[0] }}"
  when: found_fernet_master_node is undefined
  tags:
    - keystone

- name: KEY-API | _set_fernet_master_node | Set found Fernet master node
  set_fact:
    fernet_master_node: "{{ found_fernet_master_node }}"
  when: found_fernet_master_node is defined
  tags:
    - keystone
