#
# (c) Copyright 2015-2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017-2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

# Some of these libraries are already in base node install. No harm listing here
# python-httplib2 is an ansible dependency for the module uri
- name:  KEY-API | install | Install keystone dependencies
  become: yes
  package:
    state: latest
    name: "{{ item }}"
  with_items: key_api_packages
  tags:
    - keystone

- name: KEY-API | install | Add group '{{ keystone_group }}'
  become: yes
  group:
    name: "{{ keystone_group }}"
    state: present
  tags:
    - keystone

- name: KEY-API | install | Check to see if keystone user already exist
  become: yes
  getent:
    database: passwd
    key: "{{ keystone_user }}"
    fail_key: no
  tags:
    - keystone

- name: KEY-API | install | Add user '{{ keystone_user }}'
  become: yes
  user:
    name: "{{ keystone_user }}"
    group: "{{ keystone_group }}"
    createhome: no
    home: "{{ keystone_home_dir }}"
    shell: /bin/true
    state: present
  when: getent_passwd["{{ keystone_user }}"] is none
  tags:
    - keystone

- name: KEY-API | install | Create /etc/keystone directory
  become: yes
  file:
    path: "{{ item.name }}"
    owner: "{{ keystone_user }}"
    group: "{{ keystone_group }}"
    mode: "{{ item.mode }}"
    state: directory
    recurse: yes
  with_items:
    - { name: "{{ keystone_conf_dir }}", mode: "u+rwx,g+rx,o+rx" }
    - { name: "{{ keystone_conf_dir }}/ssl/certs", mode: "u+rwx,g-rwx,o-rwx" }
    - { name: "{{ keystone_conf_dir }}/domains", mode: "u+rwx,g-rwx,o-rwx" }
    - { name: "{{ keystone_fernet_dir }}", mode: "u+rwx,g-rwx,o-rwx" }
  tags:
    - keystone

- name: KEY-API | install | Create logging directory
  become: yes
  file:
    path: "{{ keystone_log_dir }}"
    owner: "{{ keystone_user }}"
    group: "{{ keystone_group }}"
    mode: 0775
    state: directory
  tags:
    - keystone


- name: KEY-API | install | Create /var/www/keystone  directory
  become: yes
  file:
    path: /var/www/keystone
    owner: "{{ keystone_user }}"
    group: "{{ keystone_group }}"
    mode: 0755
    state: directory
  tags:
    - keystone

# These two tasks are repeated so that it doesn't restart
# when u run keystone-deploy twice
- name: KEY-API | install  | Set facts for virtual install
  set_fact:
    override_virtual_install: "{{ True if is_baremetal_install == 'False' and
      (ansible_memtotal_mb < 47000) and
      (keystone_wsgi_admin_process_count == keystone_default_process_count)
      else False }}"

- name: KEY-API | install | Override process counts for virtual install
  set_fact:
    keystone_wsgi_admin_process_count: 2
    keystone_wsgi_public_process_count: 2
    keystone_wsgi_socket_timeout: 120
  when: override_virtual_install

- include: _venv_install.yml
